import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Video Conferencing App",
  description: "Generated by Johnkennedy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ClerkProvider> */}
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark-2 `}
        className={`${inter.className} bg-dark-1`}
      >
        {children}
      </body>
      {/* </ClerkProvider> */}
    </html>
  );
}
